### ISSUE TITLE
question: 질문 정리 방법 

### ISSUE THREAD

**Issue by sw0501** [sejonginterface/interviewStudy#1]
branch / 파일 / readme 어떤 방식으로 나누면 될까요

**Comment by Jeong-Rae** [comment]
다른 사람꺼 편하게 보려면 main에서 폴더로 작성하는게 편할 것 같아용
주차별로 폴더 나눠서 md로 작성할까요?

**Comment by sw0501** [comment]
주차 별로 나누게 되면  중복 질문 피할 때 각 폴더 md 다 살펴봐야 하는데 귀찮지 않을까 
근데 질문 양 자체가 많지 않다 보니까 괜찮을 것 같기도 하네

**Comment by Jeong-Rae** [comment]
그러면 인덱스 테이블 방식으로 루트 위치에는 받은 질문 목록표를 만들어두고 해당 질문에 대한 정리는 따로 자세하게 적어두는건 어때

**Comment by sw0501** [comment]
굳 좋다 루트에다가 질문 모아두고 각자 답변 상세하게 정리 하는 건 각 주차별 md에다가 하는거로
